import type { AnyQ } from "./types";

// =============================================================================
// MODULE EXAMS — recall-focused. Passing one marks a lecture as truly DONE.
// Mixed: fill-in-the-blank + multi-select + a few sharp MCQs.
// =============================================================================

export const exam_week1: AnyQ[] = [
  { id: "ex-w1-01", kind: "fill", q: "Three project constraints, in any order: time, _____, quality.",
    accept: ["cost"], explain: "Time, cost, quality.", topic: "Recall" },
  { id: "ex-w1-02", kind: "fill", q: "SMART = Specific, Measurable, _____, Relevant, Time-constrained.",
    accept: ["achievable"], explain: "A is Achievable.", topic: "Recall" },
  { id: "ex-w1-03", kind: "fill", q: "The four ways software differs (mnemonic): I-C-C-_____.",
    accept: ["F", "flexibility"], explain: "Invisibility, Complexity, Conformity, Flexibility.", topic: "Recall" },
  { id: "ex-w1-04", kind: "multi", q: "List ALL three high-level project phases.",
    options: ["Closure", "Feasibility", "Maintenance", "Planning", "Execution"], correct: [1, 3, 4],
    explain: "Feasibility → Planning → Execution.", topic: "Recall" },
  { id: "ex-w1-05", kind: "multi", q: "Name the five core PM activities introduced on slide 8.",
    options: ["Planning", "Hiring", "Scheduling", "Resource allocation", "Risk management", "Monitoring & control"],
    correct: [0, 2, 3, 4, 5], explain: "Planning, Scheduling, Resource allocation, Risk management, Monitoring & control.", topic: "Recall" },
  { id: "ex-w1-06", kind: "fill", q: "Raw details are data; processed and meaningful = _____.",
    accept: ["information"], explain: "Data vs information.", topic: "Recall" },
  { id: "ex-w1-07", kind: "fill", q: "The phase that answers 'is it worth doing?' is _____.",
    accept: ["feasibility", "feasibility study"], explain: "Feasibility study.", topic: "Recall" },
  { id: "ex-w1-08", kind: "mcq", q: "Which is NOT one of the eight management functions?",
    options: ["Planning", "Innovating", "Marketing", "Representing"], correct: 2,
    explain: "The 8: Planning, Organizing, Staffing, Directing, Controlling, Monitoring, Innovating, Representing.", topic: "Recall" },
  { id: "ex-w1-09", kind: "fill", q: "Standish: 82% of ICT projects were late and ____% over budget.",
    accept: ["43"], explain: "82% late, 43% over budget.", topic: "Recall" },
  { id: "ex-w1-10", kind: "multi", q: "Select ALL five closing key points of Lecture 1.",
    options: [
      "Projects are non-routine and uncertain",
      "Lack of visibility is a particular problem",
      "Plans rarely need to change",
      "Clear objectives that can be objectively assessed are essential",
      "Stuff happens — need for control",
      "Communicate, communicate, communicate",
    ],
    correct: [0, 1, 3, 4, 5],
    explain: "All except 'plans rarely change'. Plans must change.", topic: "Recall" },
];

export const exam_week2_1: AnyQ[] = [
  { id: "ex-w2a-01", kind: "multi", q: "List ALL four Agile Manifesto values (left-hand items only).",
    options: [
      "Individuals & interactions",
      "Comprehensive documentation",
      "Working software",
      "Customer collaboration",
      "Contract negotiation",
      "Responding to change",
    ],
    correct: [0, 2, 3, 5],
    explain: "Individuals & interactions / Working software / Customer collaboration / Responding to change.", topic: "Recall" },
  { id: "ex-w2a-02", kind: "fill", q: "The five Scrum values, by mnemonic, are C-C-R-_____-O.",
    accept: ["F", "focus"], explain: "Courage, Commitment, Respect, Focus, Openness.", topic: "Recall" },
  { id: "ex-w2a-03", kind: "multi", q: "List the three Scrum roles.",
    options: ["Product Owner", "Project Manager", "Scrum Master", "Team Member", "Release Manager"],
    correct: [0, 2, 3], explain: "PO, SM, TM.", topic: "Recall" },
  { id: "ex-w2a-04", kind: "fill", q: "Waterfall is document-driven; progress is measured by amount of _____ produced.",
    accept: ["documentation", "documents"], explain: "Documentation.", topic: "Recall" },
  { id: "ex-w2a-05", kind: "fill", q: "Agile's highest priority is to satisfy the customer through ____ and continuous delivery.",
    accept: ["early"], explain: "Early and continuous delivery.", topic: "Recall" },
  { id: "ex-w2a-06", kind: "fill", q: "Working software is the primary measure of _____.",
    accept: ["progress"], explain: "Principle 7.", topic: "Recall" },
  { id: "ex-w2a-07", kind: "mcq", q: "Which describes Waterfall, not Agile?",
    options: ["Iterative delivery", "Customer involved throughout", "Requirements fixed up-front", "Embrace change"],
    correct: 2, explain: "Waterfall: requirements up-front.", topic: "Recall" },
  { id: "ex-w2a-08", kind: "fill", q: "How many Agile principles are there?",
    accept: ["12", "twelve"], explain: "Twelve.", topic: "Recall" },
  { id: "ex-w2a-09", kind: "multi", q: "Name the three Agile frameworks the course identifies.",
    options: ["Scrum", "RAD", "Kanban", "Extreme Programming", "Spiral"],
    correct: [0, 2, 3], explain: "Scrum, Kanban, XP.", topic: "Recall" },
];

export const exam_week2_2: AnyQ[] = [
  { id: "ex-w2b-01", kind: "fill", q: "Team-added extra features no one requested = _____ plating.",
    accept: ["gold"], explain: "Gold plating.", topic: "Recall" },
  { id: "ex-w2b-02", kind: "fill", q: "Uncontrolled expansion of scope without adjusting time/cost = scope _____.",
    accept: ["creep"], explain: "Scope creep.", topic: "Recall" },
  { id: "ex-w2b-03", kind: "fill", q: "Kanban board's three columns: To Do, _____, Done.",
    accept: ["in progress"], explain: "To Do · In Progress · Done.", topic: "Recall" },
  { id: "ex-w2b-04", kind: "fill", q: "Scrum's key metric is _____; Kanban's is cycle time.",
    accept: ["velocity"], explain: "Velocity vs cycle time.", topic: "Recall" },
  { id: "ex-w2b-05", kind: "multi", q: "Which apply to Scrum (not Kanban)?",
    options: ["Continuous flow", "Fixed-length sprints", "Velocity", "Cycle time", "No prescribed roles", "Don't change sprint forecast mid-sprint"],
    correct: [1, 2, 5], explain: "Scrum: sprints, velocity, locked sprint scope.", topic: "Recall" },
  { id: "ex-w2b-06", kind: "fill", q: "Agile fixes resources and schedule and makes scope _____.",
    accept: ["variable"], explain: "Inverse of traditional PM.", topic: "Recall" },
  { id: "ex-w2b-07", kind: "multi", q: "Sprint backlog template columns include which of these?",
    options: ["User story", "Task", "Assignee", "Sprint number", "Status"], correct: [0, 1, 2, 4],
    explain: "User story, task, assignee, status.", topic: "Recall" },
  { id: "ex-w2b-08", kind: "fill", q: "XP stands for Extreme _____.",
    accept: ["programming"], explain: "Extreme Programming.", topic: "Recall" },
  { id: "ex-w2b-09", kind: "mcq", q: "Burndown chart shows…",
    options: ["Work completed by team member", "Work remaining in the project", "Estimated cost", "Number of bugs per day"],
    correct: 1, explain: "Work remaining; weakness = doesn't pinpoint process gaps.", topic: "Recall" },
];

export const exam_week3a: AnyQ[] = [
  { id: "ex-w3a-01", kind: "fill", q: "CPI formula: CPI = EV / _____.",
    accept: ["AC", "ac"], explain: "CPI = EV/AC.", topic: "Recall" },
  { id: "ex-w3a-02", kind: "fill", q: "SPI formula: SPI = EV / _____.",
    accept: ["PV", "pv"], explain: "SPI = EV/PV.", topic: "Recall" },
  { id: "ex-w3a-03", kind: "fill", q: "PERT expected duration formula numerator: t_o + ____·t_m + t_p.",
    accept: ["4"], explain: "Weighted 4× on the most likely.", topic: "Recall" },
  { id: "ex-w3a-04", kind: "fill", q: "Compute PERT: t_o=2, t_m=5, t_p=8 → t_e = ____.",
    accept: ["5", "5.0", "5.00"], explain: "(2+20+8)/6 = 5.", topic: "Recall" },
  { id: "ex-w3a-05", kind: "fill", q: "Make-or-buy break-even: lease $800/d vs purchase $12,000 + $400/d → ____ days.",
    accept: ["30"], explain: "30 days.", topic: "Recall" },
  { id: "ex-w3a-06", kind: "multi", q: "Name ALL of Boehm's seven techniques.",
    options: ["Algorithmic", "Expert judgement", "Analogy", "Parkinson", "Critical-path", "Price to win", "Top-down", "Bottom-up"],
    correct: [0, 1, 2, 3, 5, 6, 7], explain: "Critical-path is not in Boehm's seven.", topic: "Recall" },
  { id: "ex-w3a-07", kind: "multi", q: "List the FIVE reasons to plan activities.",
    options: ["Feasibility assessment", "Resource allocation", "Detailed costing", "Eliminating uncertainty", "Motivation", "Coordination"],
    correct: [0, 1, 2, 4, 5], explain: "Five reasons: feasibility, resources, costing, motivation, coordination.", topic: "Recall" },
  { id: "ex-w3a-08", kind: "fill", q: "Total Float = LS − _____ (= LF − EF).",
    accept: ["ES", "es"], explain: "TF = LS − ES.", topic: "Recall" },
  { id: "ex-w3a-09", kind: "mcq", q: "If EV > PV the project is…",
    options: ["Behind schedule", "On schedule", "Ahead of schedule", "Over budget"],
    correct: 2, explain: "EV>PV → ahead of schedule.", topic: "Recall" },
];

export const exam_week3b: AnyQ[] = [
  { id: "ex-w3b-01", kind: "fill", q: "Critical path activities have float equal to _____.",
    accept: ["0", "zero"], explain: "Float = 0.", topic: "Recall" },
  { id: "ex-w3b-02", kind: "fill", q: "At a merge in the forward pass, ES = _____ of (EF of predecessors).",
    accept: ["max", "maximum"], explain: "max(EF of predecessors).", topic: "Recall" },
  { id: "ex-w3b-03", kind: "fill", q: "At a burst in the backward pass, LF = ____ of (LS of successors).",
    accept: ["min", "minimum"], explain: "min(LS of successors).", topic: "Recall" },
  { id: "ex-w3b-04", kind: "fill", q: "Worked Example 1 critical path is A→C→G→H. Duration = ___ weeks.",
    accept: ["18"], explain: "7+6+3+2 = 18.", topic: "Recall" },
  { id: "ex-w3b-05", kind: "fill", q: "Worked Example 2 critical path is B→E→I. Duration = ____ days.",
    accept: ["25"], explain: "3+17+5 = 25.", topic: "Recall" },
  { id: "ex-w3b-06", kind: "fill", q: "Worked Example 3 critical path is _____ → G. Duration = 13 weeks.",
    accept: ["F"], explain: "F→G, 13 weeks.", topic: "Recall" },
  { id: "ex-w3b-07", kind: "multi", q: "List the two SCHEDULE COMPRESSION techniques.",
    options: ["Crashing", "Resource leveling", "Fast-tracking", "Critical chain"], correct: [0, 2],
    explain: "Crashing and Fast-tracking.", topic: "Recall" },
  { id: "ex-w3b-08", kind: "multi", q: "List the TWO buffer types in Critical Chain Method.",
    options: ["Sprint buffer", "Project buffer", "Cost buffer", "Feeding buffer"],
    correct: [1, 3], explain: "Project buffer (end of project) and feeding buffer (end of feeding path).", topic: "Recall" },
  { id: "ex-w3b-09", kind: "fill", q: "Free Float formula: FF = ES(next) − _____(current).",
    accept: ["EF", "ef"], explain: "FF = ES(next) − EF(current).", topic: "Recall" },
  { id: "ex-w3b-10", kind: "mcq", q: "Float can be NEGATIVE when…",
    options: ["The schedule is on time", "Lead time is required (behind schedule)", "There are extra resources", "Resources are leveled"],
    correct: 1, explain: "Negative float means already behind.", topic: "Recall" },
];
