import type { MCQ } from "./types";

export const week3b: MCQ[] = [
  {
    id: "w3b-001",
    q: "What is the LAST step in the 7-step CPM procedure?",
    options: [
      "Identify the activities.",
      "Enter completion time for every activity.",
      "Forward pass.",
      "Identify the float and the critical path.",
    ],
    correct: 3,
    explain: "Step 7 (last): identify the float and the critical path.",
    topic: "CPM steps",
  },
  {
    id: "w3b-002",
    q: "Which CPM step is performed first?",
    options: ["Backward pass", "Create network diagram", "Identify the activities", "Forward pass"],
    correct: 2,
    explain: "Step 1: identify the activities.",
    topic: "CPM steps",
  },
  {
    id: "w3b-003",
    q: "The Forward Pass computes:",
    options: ["LS and LF, right to left", "ES and EF, left to right", "Float at every node", "Total project cost"],
    correct: 1,
    explain: "Forward pass: ES and EF, moving left to right.",
    topic: "Forward pass",
  },
  {
    id: "w3b-004",
    q: "The Backward Pass computes:",
    options: ["ES and EF, left to right", "LS and LF, right to left", "Slack only", "Project budget"],
    correct: 1,
    explain: "Backward pass: LS and LF, right to left.",
    topic: "Backward pass",
  },
  {
    id: "w3b-005",
    q: "Forward-pass rule for EF (zero-indexed):",
    options: ["EF = LS + duration", "EF = ES + duration", "EF = ES − duration", "EF = max(LS of successors)"],
    correct: 1,
    explain: "EF = ES + duration.",
    topic: "Forward pass",
  },
  {
    id: "w3b-006",
    q: "At a MERGE (multiple predecessors), ES is computed as:",
    options: ["min(EF of predecessors)", "max(EF of predecessors)", "average(EF of predecessors)", "sum(EF of predecessors)"],
    correct: 1,
    explain: "ES = max(EF of all predecessors).",
    topic: "Forward pass",
  },
  {
    id: "w3b-007",
    q: "At a BURST (multiple successors), LF is computed as:",
    options: ["max(LS of successors)", "min(LS of successors)", "sum(LS of successors)", "average(LS of successors)"],
    correct: 1,
    explain: "LF = min(LS of all successors).",
    topic: "Backward pass",
  },
  {
    id: "w3b-008",
    q: "Total Float (zero-indexed) is:",
    options: ["LS − ES (= LF − EF)", "ES − LS", "EF − LF", "EF + LS"],
    correct: 0,
    explain: "Total Float = LS − ES, equivalently LF − EF.",
    topic: "Float",
  },
  {
    id: "w3b-009",
    q: "The activities on the critical path have float equal to:",
    options: ["1", "0", "Project duration", "Maximum total float"],
    correct: 1,
    explain: "Critical path activities have float = 0.",
    topic: "Critical path",
  },
  {
    id: "w3b-010",
    q: "Float can be NEGATIVE when:",
    options: ["The schedule is on time.", "Lead time is required (already behind).", "There are extra resources.", "The project has no successor activities."],
    correct: 1,
    explain: "Negative float arises when lead time is required — i.e., already behind.",
    topic: "Float",
  },
  {
    id: "w3b-011",
    q: "In Worked Example 1 (zero-indexed), the project duration is:",
    options: ["13 weeks", "18 weeks", "25 weeks", "30 weeks"],
    correct: 1,
    explain: "Example 1 critical path A→C→G→H gives 7+6+3+2 = 18 weeks.",
    topic: "Examples",
  },
  {
    id: "w3b-012",
    q: "The critical path in Worked Example 1 is:",
    options: ["A → C → G → H", "A → B → D → H", "B → D → E → H", "A → C → E → H"],
    correct: 0,
    explain: "Critical path = A → C → G → H (float = 0 throughout).",
    topic: "Examples",
  },
  {
    id: "w3b-013",
    q: "Worked Example 2 uses 1-indexed days. Its convention is:",
    options: [
      "FINISH = START + TIME",
      "FINISH = START + TIME − 1; successor starts at predecessor EF + 1",
      "FINISH = START − TIME",
      "FINISH = START × TIME",
    ],
    correct: 1,
    explain: "1-indexed: FINISH = START + TIME − 1. Successors start at predecessor EF + 1.",
    topic: "Examples",
  },
  {
    id: "w3b-014",
    q: "Worked Example 2 — project duration in days:",
    options: ["18 days", "22 days", "25 days", "30 days"],
    correct: 2,
    explain: "Critical path B → E → I gives 3 + 17 + 5 = 25 days.",
    topic: "Examples",
  },
  {
    id: "w3b-015",
    q: "Worked Example 2 — critical path is:",
    options: ["A → D → G", "B → E → I", "C → F → J", "A → D → H"],
    correct: 1,
    explain: "Critical path = B → E → I (slack = 0).",
    topic: "Examples",
  },
  {
    id: "w3b-016",
    q: "Worked Example 3 (hardware/software project) — project duration is:",
    options: ["10 weeks", "11 weeks", "13 weeks", "18 weeks"],
    correct: 2,
    explain: "Critical path F → G = 10 + 3 = 13 weeks.",
    topic: "Examples",
  },
  {
    id: "w3b-017",
    q: "Worked Example 3 — critical path is:",
    options: ["A → C → H", "B → D → H", "F → G", "B → E → G"],
    correct: 2,
    explain: "Critical path = F → G.",
    topic: "Examples",
  },
  {
    id: "w3b-018",
    q: "Free Float is defined as:",
    options: [
      "Time a task can be delayed without delaying project completion.",
      "Time a task can be delayed without delaying a SUCCESSOR task.",
      "Total time slack on a critical activity.",
      "The same as total float.",
    ],
    correct: 1,
    explain: "Free Float = time a task can be delayed without delaying a successor.",
    topic: "Float",
  },
  {
    id: "w3b-019",
    q: "Total Float is defined as:",
    options: [
      "Time a task can be delayed without delaying a successor.",
      "Time a task can be delayed without delaying project completion.",
      "Float that is always equal to free float.",
      "Time saved by parallelism.",
    ],
    correct: 1,
    explain: "Total Float = delay tolerance without delaying project completion.",
    topic: "Float",
  },
  {
    id: "w3b-020",
    q: "A network can have:",
    options: [
      "Exactly one critical path always.",
      "More than one critical path if multiple paths tie for the longest.",
      "No critical path at all.",
      "Only critical paths through start and end nodes only.",
    ],
    correct: 1,
    explain: "Multiple critical paths can exist if paths tie for the longest duration.",
    topic: "Critical path",
  },
  {
    id: "w3b-021",
    q: "Critical Chain Method differs from CPM by:",
    options: [
      "Ignoring duration estimates.",
      "Accounting for resource constraints and protecting with shared buffers.",
      "Eliminating critical paths.",
      "Requiring AoA notation.",
    ],
    correct: 1,
    explain: "Critical Chain accounts for resource limits and uses aggregated buffers (project + feeding).",
    topic: "Critical Chain",
  },
  {
    id: "w3b-022",
    q: "A PROJECT BUFFER in Critical Chain is added:",
    options: [
      "At the start of each activity.",
      "At the end of every activity.",
      "At the end of the project.",
      "Between every two activities.",
    ],
    correct: 2,
    explain: "Project buffer sits at the end of the project; feeding buffers sit at end of feeding activities.",
    topic: "Critical Chain",
  },
  {
    id: "w3b-023",
    q: "A FEEDING BUFFER in Critical Chain is added:",
    options: [
      "At the end of a feeding activity (where it joins the critical chain).",
      "At the end of the project.",
      "Only at the very start.",
      "Inside every critical-chain activity.",
    ],
    correct: 0,
    explain: "Feeding buffers go at the end of feeding activities meeting the critical chain.",
    topic: "Critical Chain",
  },
  {
    id: "w3b-024",
    q: "Resource Leveling is applied:",
    options: [
      "Before the activity list exists.",
      "To a schedule already developed using CPM.",
      "Only to the budget plan.",
      "Only to risk registers.",
    ],
    correct: 1,
    explain: "Resource leveling is applied to a CPM-developed schedule to even out resource demand.",
    topic: "Resource leveling",
  },
  {
    id: "w3b-025",
    q: "A possible SIDE EFFECT of resource leveling is:",
    options: [
      "Reducing the project budget automatically.",
      "Changing the critical path / extending project duration.",
      "Eliminating all float.",
      "Increasing scope.",
    ],
    correct: 1,
    explain: "Leveling may change the critical path or extend duration.",
    topic: "Resource leveling",
  },
  {
    id: "w3b-026",
    q: "Schedule Compression aims to:",
    options: [
      "Reduce scope.",
      "Shorten the schedule WITHOUT changing scope.",
      "Add buffer time.",
      "Convert AoA to AoN.",
    ],
    correct: 1,
    explain: "Schedule compression shortens the schedule without changing scope.",
    topic: "Compression",
  },
  {
    id: "w3b-027",
    q: "Crashing is best characterised as:",
    options: [
      "Running activities in parallel.",
      "Shortening duration for the LEAST incremental cost (overtime, extra resources).",
      "Removing activities entirely.",
      "Adding contingency time.",
    ],
    correct: 1,
    explain: "Crashing shortens duration by adding cost/resources for the smallest incremental cost.",
    topic: "Compression",
  },
  {
    id: "w3b-028",
    q: "Fast tracking is best characterised as:",
    options: [
      "Adding overtime hours.",
      "Doing activities in PARALLEL rather than sequentially (only if they can overlap).",
      "Shortening durations by paying suppliers more.",
      "Cutting documentation.",
    ],
    correct: 1,
    explain: "Fast tracking runs activities in parallel — adds risk of rework.",
    topic: "Compression",
  },
  {
    id: "w3b-029",
    q: "Compared to fast tracking, crashing primarily:",
    options: ["Adds rework risk", "Adds cost", "Reduces scope", "Increases float"],
    correct: 1,
    explain: "Crashing buys time with money (cost). Fast tracking buys time with parallelism (rework risk).",
    topic: "Compression",
  },
  {
    id: "w3b-030",
    q: "A schedule BASELINE is:",
    options: [
      "The first draft schedule, unapproved.",
      "An accepted, approved schedule used for comparison against actuals.",
      "A list of milestones with no dates.",
      "The contingency reserve plan.",
    ],
    correct: 1,
    explain: "Schedule baseline = accepted/approved schedule used to compare planned vs actual.",
    topic: "Baseline",
  },
  {
    id: "w3b-031",
    q: "Project schedules can be presented as:",
    options: [
      "Only tabular forms (e.g., milestone tables).",
      "Only Gantt charts.",
      "Tabular forms AND graphical forms (Gantt, network diagrams).",
      "Only via burndown charts.",
    ],
    correct: 2,
    explain: "Tabular (milestone schedule) AND graphical (Gantt, network diagrams).",
    topic: "Forms",
  },
  {
    id: "w3b-032",
    q: "If LS = 13 and ES = 6 on an activity, the Total Float is:",
    options: ["6", "7", "13", "19"],
    correct: 1,
    explain: "TF = LS − ES = 13 − 6 = 7.",
    topic: "Float",
  },
  {
    id: "w3b-033",
    q: "An activity has ES=10, EF=14. Its successor has ES=15. Free Float of the current activity is:",
    options: ["0", "1", "4", "5"],
    correct: 1,
    explain: "FF = ES(next) − EF(current) = 15 − 14 = 1.",
    topic: "Float",
  },
];
