import type { MCQ } from "./types";

export const week2_2: MCQ[] = [
  {
    id: "w2b-001",
    q: "A Work Breakdown Structure (WBS) decomposes a project into:",
    options: [
      "A flat prioritized list of user stories.",
      "A hierarchy of deliverables/tasks broken into progressively smaller pieces.",
      "A list of sprint backlogs.",
      "A timeline of milestones only.",
    ],
    correct: 1,
    explain: "WBS = hierarchical decomposition of deliverables/tasks into smaller, manageable pieces.",
    topic: "WBS",
  },
  {
    id: "w2b-002",
    q: "Scope creep is best defined as:",
    options: [
      "Adding extra features the customer didn't ask for.",
      "Uncontrolled changes/expansions to project scope without adjusting time, cost, or resources.",
      "Removing requirements to deliver faster.",
      "Replanning the schedule mid-project.",
    ],
    correct: 1,
    explain: "Scope creep = uncontrolled expansion of scope without adjusting time/cost/resources.",
    topic: "Scope creep",
  },
  {
    id: "w2b-003",
    q: "Which is a typical CAUSE of scope creep?",
    options: [
      "Strict change-control board.",
      "Incomplete or inadequate scope statements.",
      "Excessive monitoring of project progress.",
      "Detailed up-front requirements review.",
    ],
    correct: 1,
    explain: "Causes include client interference, miscommunication, incomplete scope statements, insufficient monitoring, external trends.",
    topic: "Scope creep",
  },
  {
    id: "w2b-004",
    q: "Gold plating is best defined as:",
    options: [
      "The team adds extra features that were NOT part of the original scope.",
      "The customer requests more features without paying.",
      "Pre-purchasing extra hardware in case it is needed.",
      "Adding a final review layer to ensure quality.",
    ],
    correct: 0,
    explain: "Gold plating = team adds unrequested extras as 'freebies' for the client.",
    topic: "Gold plating",
  },
  {
    id: "w2b-005",
    q: "Which is NOT listed as a cause of gold plating?",
    options: [
      "Going above and beyond.",
      "Showing off skills.",
      "Distracting from defects.",
      "Reducing the project's budget.",
    ],
    correct: 3,
    explain: "Causes: going above and beyond, showing off, distracting from defects.",
    topic: "Gold plating",
  },
  {
    id: "w2b-006",
    q: "What is the key difference between scope creep and gold plating?",
    options: [
      "Scope creep is internal; gold plating is external.",
      "Scope creep is often client-initiated; gold plating is initiated by the project team.",
      "They mean the same thing in practice.",
      "Gold plating is always authorised; scope creep is not.",
    ],
    correct: 1,
    explain: "Scope creep usually from client/external; gold plating from the team (unrequested freebies).",
    topic: "Compare",
  },
  {
    id: "w2b-007",
    q: "What does the Product Backlog contain?",
    options: [
      "Only tasks for the current sprint.",
      "The full list of future activities/requirements still to do.",
      "Completed user stories only.",
      "A Gantt chart of deliverables.",
    ],
    correct: 1,
    explain: "Product backlog = the full list of future activities/requirements.",
    topic: "Scrum artifacts",
  },
  {
    id: "w2b-008",
    q: "A Sprint Backlog template typically has columns for:",
    options: [
      "Start date, end date, owner, status",
      "User story, task, assignee, status",
      "ID, title, description, priority",
      "Epic, theme, story points, owner",
    ],
    correct: 1,
    explain: "Sprint backlog columns: user story, task, assignee, status.",
    topic: "Scrum artifacts",
  },
  {
    id: "w2b-009",
    q: "What does a Burndown Chart show?",
    options: [
      "How much work has been completed across all sprints.",
      "How much work remains in the project — a summary view.",
      "The number of bugs per day.",
      "Resource utilisation by team member.",
    ],
    correct: 1,
    explain: "Burndown chart shows work remaining; gives a quick overview but is poor at pinpointing process gaps.",
    topic: "Scrum artifacts",
  },
  {
    id: "w2b-010",
    q: "What is the main LIMITATION of a burndown chart?",
    options: [
      "It cannot be drawn manually.",
      "It can identify only single-person blockers.",
      "It is limited at identifying specific process gaps — shows summary only.",
      "It cannot show velocity.",
    ],
    correct: 2,
    explain: "Burndown only shows total work; it does not pinpoint specific process gaps.",
    topic: "Scrum artifacts",
  },
  {
    id: "w2b-011",
    q: "What is the daily stand-up meant to surface?",
    options: [
      "Velocity charts and historical averages.",
      "Progress, blockers, and plans for the day.",
      "Sprint scope changes only.",
      "Long-term roadmap decisions.",
    ],
    correct: 1,
    explain: "Daily stand-up: short daily meeting on progress, blockers, plans for the day.",
    topic: "Scrum artifacts",
  },
  {
    id: "w2b-012",
    q: "How does Agile 'break' the Iron Triangle?",
    options: [
      "By fixing all three constraints at once.",
      "By fixing scope and flexing resources and schedule.",
      "By fixing resources and schedule while making scope variable.",
      "By removing the quality constraint.",
    ],
    correct: 2,
    explain: "Agile fixes resources/schedule and makes scope variable — the inverse of traditional PM.",
    topic: "Iron Triangle",
  },
  {
    id: "w2b-013",
    q: "Traditional PM (Iron Triangle) treats scope as:",
    options: ["Variable, time and cost fixed", "Fixed, time and cost flex to deliver it", "Optional", "Determined sprint-by-sprint"],
    correct: 1,
    explain: "Traditional: scope is fixed; time/cost flex to deliver it.",
    topic: "Iron Triangle",
  },
  {
    id: "w2b-014",
    q: "Project management vs Product management — which focuses on the PRODUCT itself?",
    options: ["Project management", "Product management", "Both focus on tasks", "Neither — both focus on schedule"],
    correct: 1,
    explain: "Project management = manage tasks/activities for schedule & budget. Product management = manage the product.",
    topic: "Compare",
  },
  {
    id: "w2b-015",
    q: "A common SYMPTOM of carrying traditional PM bias into Agile is:",
    options: [
      "Holding daily stand-ups.",
      "Structuring product backlogs like WBS hierarchies.",
      "Using user stories.",
      "Embracing sprint reviews.",
    ],
    correct: 1,
    explain: "Forcing a product backlog into a WBS-style hierarchy reveals traditional-PM bias.",
    topic: "Compare",
  },
  {
    id: "w2b-016",
    q: "Which best contrasts WBS and Product Backlog?",
    options: [
      "WBS is hierarchical; Product Backlog is a prioritized flat list.",
      "WBS is for Agile; Product Backlog is for Waterfall.",
      "WBS is rebuilt each sprint; Product Backlog is fixed.",
      "There is no real difference.",
    ],
    correct: 0,
    explain: "WBS = hierarchical decomposition (traditional). Product Backlog = prioritized list of stories (Agile).",
    topic: "Compare",
  },
  {
    id: "w2b-017",
    q: "Kanban is best described as:",
    options: [
      "A scripting language for project plans.",
      "A framework that implements Agile via visualised, transparent workflow.",
      "A subset of Waterfall focused on flow.",
      "A risk management approach.",
    ],
    correct: 1,
    explain: "Kanban implements Agile with real-time capacity communication and full work transparency on a board.",
    topic: "Kanban",
  },
  {
    id: "w2b-018",
    q: "A typical Kanban board has columns:",
    options: ["Backlog · Sprint · Release", "To Do · In Progress · Done", "Plan · Build · Ship", "Open · Closed · Verified"],
    correct: 1,
    explain: "Standard Kanban columns: To Do, In Progress, Done.",
    topic: "Kanban",
  },
  {
    id: "w2b-019",
    q: "Virtual Kanban boards are valued mainly for:",
    options: [
      "Lower hardware cost.",
      "Traceability, collaboration, and accessibility from multiple locations.",
      "Eliminating the need for Scrum Masters.",
      "Removing the need for daily stand-ups.",
    ],
    correct: 1,
    explain: "Virtual boards offer traceability, collaboration, and remote accessibility.",
    topic: "Kanban",
  },
  {
    id: "w2b-020",
    q: "Scrum vs Kanban — which uses fixed-length sprints?",
    options: ["Scrum", "Kanban", "Both", "Neither"],
    correct: 0,
    explain: "Scrum runs fixed-length sprints; Kanban is continuous flow.",
    topic: "Compare",
  },
  {
    id: "w2b-021",
    q: "Which key metric is associated with KANBAN?",
    options: ["Velocity", "Story points per epic", "Cycle time", "Burndown slope"],
    correct: 2,
    explain: "Kanban's key metric is cycle time; Scrum's is velocity.",
    topic: "Compare",
  },
  {
    id: "w2b-022",
    q: "Which key metric is associated with SCRUM?",
    options: ["Cycle time", "Velocity", "Throughput", "Lead time"],
    correct: 1,
    explain: "Scrum's key metric is velocity; Kanban's is cycle time.",
    topic: "Compare",
  },
  {
    id: "w2b-023",
    q: "Scrum's change philosophy is:",
    options: [
      "Change can happen at any time.",
      "Teams should not change the sprint forecast during a sprint.",
      "Change requires customer sign-off only.",
      "Change is delegated to the PMO.",
    ],
    correct: 1,
    explain: "Scrum: don't change the sprint forecast mid-sprint — it harms estimation learning.",
    topic: "Compare",
  },
  {
    id: "w2b-024",
    q: "Kanban's change philosophy is:",
    options: [
      "Locked once a sprint starts.",
      "Change can happen at any time.",
      "Changes go to a release-approval board.",
      "Changes only allowed at retrospectives.",
    ],
    correct: 1,
    explain: "Kanban allows change at any time — continuous flow.",
    topic: "Compare",
  },
  {
    id: "w2b-025",
    q: "Kanban's role structure is:",
    options: [
      "Product Owner, Scrum Master, Developers.",
      "Prescribed roles: PO, SM, Tester.",
      "No prescribed roles — at the team's discretion.",
      "Project Manager and Tech Lead only.",
    ],
    correct: 2,
    explain: "Kanban has no prescribed roles; team decides.",
    topic: "Compare",
  },
  {
    id: "w2b-026",
    q: "What does XP stand for?",
    options: ["Extra Productivity", "Extended Process", "Extreme Programming", "Express Pipeline"],
    correct: 2,
    explain: "XP = Extreme Programming.",
    topic: "XP",
  },
  {
    id: "w2b-027",
    q: "XP emphasises:",
    options: [
      "Heavy documentation and slow feedback loops.",
      "Frequent and continuous feedback, collaboration, and rapid iterative development.",
      "Centralised approval before any code is written.",
      "Single annual releases.",
    ],
    correct: 1,
    explain: "XP is built on frequent feedback, collaboration, rapid iterative dev/deployment.",
    topic: "XP",
  },
  {
    id: "w2b-028",
    q: "Agile and project management are related — which is true?",
    options: [
      "Agile = project management.",
      "Project management is a subset of Agile.",
      "Agile is one of many approaches that can be applied to project management.",
      "Project management replaces Agile.",
    ],
    correct: 2,
    explain: "Agile is a specific methodology; project management is the broader discipline.",
    topic: "Compare",
  },
  {
    id: "w2b-029",
    q: "A 'freebie' feature delivered with no time/cost adjustment is an example of:",
    options: ["Scope creep", "Gold plating", "Continuous delivery", "Resource leveling"],
    correct: 1,
    explain: "Gold plating = team-added freebies beyond original scope.",
    topic: "Gold plating",
  },
  {
    id: "w2b-030",
    q: "A KEY weakness of Waterfall reflected in scope problems is:",
    options: [
      "Heavy documentation that's easy to update.",
      "Requirements fixed up-front, which struggle with later change.",
      "Daily customer involvement.",
      "Continuous delivery.",
    ],
    correct: 1,
    explain: "Waterfall demands requirements up-front — change-handling is poor compared to Agile.",
    topic: "Compare",
  },
];
