import type { MCQ } from "./types";

export const week1: MCQ[] = [
  {
    id: "w1-001",
    q: "Per the Longmans dictionary roots used in the course, what are the two key ideas extracted from the definition of a project?",
    options: ["Cost and quality", "Planning and size", "Risk and resource", "Schedule and scope"],
    correct: 1,
    explain: "The course extracts planning and size of task from the dictionary definitions.",
    topic: "Definitions",
  },
  {
    id: "w1-002",
    q: "Which definition of a project is given on the course slides?",
    options: [
      "A repeating effort to deliver a standard product within scope.",
      "A temporary effort to create a unique product or service, with constraints and risks on cost, schedule, and performance.",
      "An exploratory undertaking aimed at uncertain outcomes.",
      "A continuous operation that improves an existing system.",
    ],
    correct: 1,
    explain: "A project is a temporary effort producing a unique product/service, subject to cost/schedule/performance constraints.",
    topic: "Definitions",
  },
  {
    id: "w1-003",
    q: "Which three constraints anchor a project according to the slide diagram?",
    options: ["Risk, scope, schedule", "Time, cost, quality", "Cost, people, tools", "Scope, time, people"],
    correct: 1,
    explain: "The three constraints are time, cost, and quality.",
    topic: "Constraints",
  },
  {
    id: "w1-004",
    q: "What is a software project?",
    options: [
      "Any maintenance task on existing code.",
      "A project whose deliverable is a software system (source code and working system).",
      "A project where the deliverable is hardware that runs software.",
      "Any consulting engagement involving software.",
    ],
    correct: 1,
    explain: "A software project produces a software system — the source code and working system built from it.",
    topic: "Definitions",
  },
  {
    id: "w1-005",
    q: "Which of these is NOT one of the five core PM activities introduced on slide 8?",
    options: ["Planning", "Scheduling", "Marketing", "Risk management"],
    correct: 2,
    explain: "The five are Planning, Scheduling, Resource allocation, Risk management, Monitoring & control. Marketing is not listed.",
    topic: "PM activities",
  },
  {
    id: "w1-006",
    q: "Approximately what fraction of ICT projects are successful, according to the Standish Group figures cited?",
    options: ["About one half", "About one third", "About one quarter", "About two thirds"],
    correct: 1,
    explain: "Standish Group: only about one third of ICT projects are successful.",
    topic: "Statistics",
  },
  {
    id: "w1-007",
    q: "What percentage of ICT projects were reported as late in the Standish figures?",
    options: ["43%", "71%", "82%", "94%"],
    correct: 2,
    explain: "82% were late; 43% exceeded their budget.",
    topic: "Statistics",
  },
  {
    id: "w1-008",
    q: "What percentage of ICT projects exceeded their budget?",
    options: ["29%", "43%", "71%", "82%"],
    correct: 1,
    explain: "43% exceeded budget; 82% were late.",
    topic: "Statistics",
  },
  {
    id: "w1-009",
    q: "From the slide pie charts, what was the failure rate for LARGE projects?",
    options: ["71%", "82%", "91%", "94%"],
    correct: 3,
    explain: "Large projects fail at 94%, medium at 91%, all-projects at 71%.",
    topic: "Statistics",
  },
  {
    id: "w1-010",
    q: "What was the UK government's ICT contract spend in 2003-4 (per the slides)?",
    options: ["£1.4 billion", "£2.3 billion", "£3.5 billion", "£900 million"],
    correct: 1,
    explain: "£2.3 billion on ICT, compared to £1.4 billion on road building.",
    topic: "Statistics",
  },
  {
    id: "w1-011",
    q: "On the Jobs–Projects–Exploration spectrum, where do projects sit?",
    options: [
      "On the routine, low-uncertainty end.",
      "On the very high-uncertainty, exploration end.",
      "In the middle of the spectrum.",
      "Outside the spectrum — they are unrelated.",
    ],
    correct: 2,
    explain: "Projects sit in the middle: more uncertain than jobs, less than exploration.",
    topic: "Categorization",
  },
  {
    id: "w1-012",
    q: "Which characteristic is NOT listed as making a task more 'project-like'?",
    options: ["Non-routine", "Aimed at a specific target", "Always carried out by permanent teams", "Made up of several different phases"],
    correct: 2,
    explain: "Projects are typically carried out by temporary work groups, not permanent teams.",
    topic: "Characteristics",
  },
  {
    id: "w1-013",
    q: "In a 'Quality culture', the manager is best described as:",
    options: ["A controller solving problems at the top", "A coach of the team they lead", "A gatekeeper of resources", "A reporter to senior management"],
    correct: 1,
    explain: "Quality culture treats managers as coaches: they communicate vision, remove barriers, build trust, train, and reward.",
    topic: "Management approaches",
  },
  {
    id: "w1-014",
    q: "The four distinguishing characteristics of software projects (I-C-C-F) are:",
    options: [
      "Innovation, Complexity, Cost, Flexibility",
      "Invisibility, Complexity, Conformity, Flexibility",
      "Invisibility, Cost, Conformity, Functionality",
      "Innovation, Communication, Conformity, Feedback",
    ],
    correct: 1,
    explain: "I-C-C-F: Invisibility, Complexity, Conformity, Flexibility.",
    topic: "Software differences",
  },
  {
    id: "w1-015",
    q: "Why is 'invisibility' a distinguishing characteristic of software projects?",
    options: [
      "Software is invisible to managers.",
      "Progress is not immediately visible — you can't see code progressing like a building.",
      "Software is invisible to customers.",
      "Software has no measurable cost.",
    ],
    correct: 1,
    explain: "Progress in a software project is not immediately visible to the eye.",
    topic: "Software differences",
  },
  {
    id: "w1-016",
    q: "What is the first phase in the three high-level project activities?",
    options: ["Planning", "Execution", "Feasibility study", "Closure"],
    correct: 2,
    explain: "Feasibility (is it worth doing?) precedes Planning (how?), which precedes Execution (do it!).",
    topic: "Phases",
  },
  {
    id: "w1-017",
    q: "When is the planning phase carried out?",
    options: [
      "Before feasibility, as a preliminary step.",
      "Always before execution, regardless of feasibility.",
      "Only if the project is feasible.",
      "Continuously, throughout the project.",
    ],
    correct: 2,
    explain: "Planning is only done if the project is shown to be feasible.",
    topic: "Phases",
  },
  {
    id: "w1-018",
    q: "In ISO 12207, which activity is responsible for ELICITING what the client needs?",
    options: ["Architecture design", "Requirements analysis", "Qualification testing", "Installation"],
    correct: 1,
    explain: "Requirements analysis covers elicitation (what does the client need?) and analysis.",
    topic: "ISO 12207",
  },
  {
    id: "w1-019",
    q: "In ISO 12207, where do SOFTWARE requirements come from?",
    options: [
      "They are the same as system requirements.",
      "They are written directly by the client.",
      "They emerge from architecture design.",
      "They come out of qualification testing.",
    ],
    correct: 2,
    explain: "Architecture design is based on system requirements; software requirements emerge from it.",
    topic: "ISO 12207",
  },
  {
    id: "w1-020",
    q: "Qualification testing in ISO 12207 tests:",
    options: ["Only the software components", "Only the database", "The system (not just the software)", "Only the user interface"],
    correct: 2,
    explain: "Qualification testing tests the SYSTEM, not just the software.",
    topic: "ISO 12207",
  },
  {
    id: "w1-021",
    q: "Which ISO 12207 stage covers setting up standing data, system parameters, and user training?",
    options: ["Code and test", "Integration", "Installation", "Acceptance support"],
    correct: 2,
    explain: "Installation is the process of making the system operational, including training and standing data.",
    topic: "ISO 12207",
  },
  {
    id: "w1-022",
    q: "Acceptance support includes:",
    options: ["Only bug fixing", "Only operations training", "Maintenance and enhancement", "Hardware procurement"],
    correct: 2,
    explain: "Acceptance support covers maintenance AND enhancement.",
    topic: "ISO 12207",
  },
  {
    id: "w1-023",
    q: "The difference between an in-house and an out-sourced project is best described by:",
    options: [
      "Whether the client and developers belong to the same organization.",
      "Whether the project is for a government client.",
      "Whether the team uses Agile.",
      "Whether the project has a fixed budget.",
    ],
    correct: 0,
    explain: "In-house = same organization; Out-sourced = different organizations.",
    topic: "In-house vs Out-sourced",
  },
  {
    id: "w1-024",
    q: "What term describes a SET of methods?",
    options: ["Plan", "Process", "Method", "Methodology"],
    correct: 3,
    explain: "Method = a way of working; Methodology = a set of methods.",
    topic: "Plans/methods",
  },
  {
    id: "w1-025",
    q: "Which of the following is NOT one of the categorization axes given for projects?",
    options: [
      "Voluntary vs Compulsory",
      "Information systems vs Embedded systems",
      "Objective-based vs Product-based",
      "Open-source vs Proprietary",
    ],
    correct: 3,
    explain: "Open-source vs proprietary is not used. The three axes are: voluntary/compulsory, information/embedded, objective/product-based.",
    topic: "Categorization",
  },
  {
    id: "w1-026",
    q: "Different stakeholders may have different objectives. What is the recommended response?",
    options: [
      "Pick the stakeholder with the most power and follow them.",
      "Define a single set of common project objectives.",
      "Allow each stakeholder to define their own success criteria.",
      "Ignore stakeholders outside the team.",
    ],
    correct: 1,
    explain: "You must define common project objectives to reconcile differing stakeholder objectives.",
    topic: "Stakeholders",
  },
  {
    id: "w1-027",
    q: "Which of the following is part of the project TEAM (not 'other stakeholders')?",
    options: ["Operation Managers", "Sponsor", "Business Partners", "Government"],
    correct: 1,
    explain: "Project team: Sponsor, Project Manager, Team Members. The others are 'Other Stakeholders'.",
    topic: "Stakeholders",
  },
  {
    id: "w1-028",
    q: "Which of these is the BEST informal phrasing of a project objective?",
    options: [
      "We will do the work properly.",
      "We will use the best methodology available.",
      "The project will be regarded as a success if ……….",
      "We will deliver software on time.",
    ],
    correct: 2,
    explain: "Objectives are framed as 'post-conditions': 'The project will be regarded as a success if …'.",
    topic: "Objectives",
  },
  {
    id: "w1-029",
    q: "In SMART, what does the 'R' stand for?",
    options: ["Realistic", "Relevant", "Repeatable", "Risk-aware"],
    correct: 1,
    explain: "SMART: Specific, Measurable, Achievable, Relevant, Time-constrained.",
    topic: "SMART",
  },
  {
    id: "w1-030",
    q: "In SMART, the 'M' means an objective is:",
    options: ["Manageable by one person", "Measurable — satisfaction can be objectively judged", "Motivating to the team", "Methodologically sound"],
    correct: 1,
    explain: "Measurable means satisfaction of the objective can be objectively judged.",
    topic: "SMART",
  },
  {
    id: "w1-031",
    q: "Which BEST captures the relationship between an objective and a goal/sub-objective?",
    options: [
      "Goals are bigger than objectives.",
      "Goals are steps along the way to achieving the objective.",
      "Goals and objectives are the same thing.",
      "Goals are only for individuals; objectives only for teams.",
    ],
    correct: 1,
    explain: "Goals/sub-objectives are steps along the way; an individual may achieve their goal but not the whole objective.",
    topic: "Goals",
  },
  {
    id: "w1-032",
    q: "If overall objective = 'user satisfaction with the software product', which is a developer GOAL?",
    options: ["Accurate requirements", "Reliable software", "High repeat business", "Low number of complaints"],
    correct: 1,
    explain: "Analyst goal: accurate requirements. Developer goal: reliable software.",
    topic: "Goals",
  },
  {
    id: "w1-033",
    q: "Measures of effectiveness are best characterised as:",
    options: [
      "Subjective surveys completed by the manager.",
      "Practical tests that can be objectively assessed.",
      "Self-reports from each team member.",
      "Estimated costs that may be adjusted later.",
    ],
    correct: 1,
    explain: "Effectiveness is measured by a practical test that can be objectively assessed.",
    topic: "Effectiveness",
  },
  {
    id: "w1-034",
    q: "The business case requires that:",
    options: [
      "Costs and benefits balance exactly.",
      "Benefits of the delivered project outweigh the costs (including development and operation).",
      "Quantifiable benefits exceed quantifiable costs only.",
      "Operational costs are excluded from the comparison.",
    ],
    correct: 1,
    explain: "Benefits must outweigh costs; costs include development AND operation.",
    topic: "Business case",
  },
  {
    id: "w1-035",
    q: "If a project is running out of time, the project-triangle trade-off rule suggests you can recover by:",
    options: [
      "Increasing quality and reducing cost.",
      "Reducing scope or increasing cost.",
      "Reducing scope and reducing cost simultaneously.",
      "Adding new objectives.",
    ],
    correct: 1,
    explain: "Trade-off rule: reduce scope OR increase cost to protect the time corner.",
    topic: "Iron triangle",
  },
  {
    id: "w1-036",
    q: "Which management function is described as 'making arrangements'?",
    options: ["Planning", "Organizing", "Directing", "Controlling"],
    correct: 1,
    explain: "Organizing brings together physical/financial/human resources — 'making arrangements'.",
    topic: "Management functions",
  },
  {
    id: "w1-037",
    q: "Which management function is described as 'selecting the right people for the job'?",
    options: ["Directing", "Organizing", "Staffing", "Innovating"],
    correct: 2,
    explain: "Staffing is manning the organizational structure and keeping it manned.",
    topic: "Management functions",
  },
  {
    id: "w1-038",
    q: "Which management function covers 'liaising with clients, users, developers, and other stakeholders'?",
    options: ["Directing", "Representing", "Monitoring", "Organizing"],
    correct: 1,
    explain: "Representing = liaising with clients, users, developers, and other stakeholders.",
    topic: "Management functions",
  },
  {
    id: "w1-039",
    q: "In the management control loop, what comes IMMEDIATELY after data processing?",
    options: ["Implementation", "Data collection", "Information (used for decisions/plans)", "Modelling"],
    correct: 2,
    explain: "Data → Data processing → Information → Decisions/plans → Implementation → back to the real world.",
    topic: "Control loop",
  },
  {
    id: "w1-040",
    q: "The classic distinction the lecture draws is:",
    options: [
      "Data is meaningful, information is raw.",
      "Data and information mean the same thing.",
      "Data is raw details; information is processed and meaningful.",
      "Information requires modelling; data requires comparison.",
    ],
    correct: 2,
    explain: "Data = raw (e.g., 6,000 docs at X). Information = meaningful (e.g., 100 docs/day).",
    topic: "Control loop",
  },
  {
    id: "w1-041",
    q: "The 'triple constraint' in basic PM terms is:",
    options: ["Cost, time, scope (quality at the centre)", "Cost, risk, schedule", "Quality, communication, leadership", "Scope, risk, quality"],
    correct: 0,
    explain: "Triple constraint corners: Scope, Time, Cost. Quality sits at the centre.",
    topic: "Iron triangle",
  },
  {
    id: "w1-042",
    q: "Hard vs soft PM skills — which is a HARD skill?",
    options: ["Empathy", "Listening", "Knowing PM tools and techniques", "Team motivation"],
    correct: 2,
    explain: "Hard = product knowledge + PM tools/techniques. Soft = working with people.",
    topic: "PM skills",
  },
  {
    id: "w1-043",
    q: "Which is NOT in the six suggested PM skill areas listed?",
    options: ["Leadership", "Coping", "Coding", "Technology"],
    correct: 2,
    explain: "The six are Communication, Organizational, Team-building, Leadership, Coping, Technology.",
    topic: "PM skills",
  },
  {
    id: "w1-044",
    q: "Which of these is a 'manager's-point-of-view' common problem with software projects?",
    options: [
      "Lack of internet access.",
      "Lack of techniques to make progress visible.",
      "Excessive automated testing.",
      "Too much user feedback.",
    ],
    correct: 1,
    explain: "Listed problems include poor estimates, lack of quality standards, lack of techniques to make progress visible, poor role definition, incorrect success criteria.",
    topic: "Problems",
  },
  {
    id: "w1-045",
    q: "Which is one of the FIVE key points concluding Lecture 1?",
    options: [
      "Projects are routine and predictable.",
      "Clear objectives that can be objectively assessed are essential.",
      "Detailed plans rarely need to change.",
      "Communication is overrated for project managers.",
    ],
    correct: 1,
    explain: "Key points: projects non-routine; lack of visibility; clear objectives essential; need for control; communicate, communicate, communicate.",
    topic: "Key points",
  },
];
