import type { MCQ } from "./types";

export const week3a: MCQ[] = [
  {
    id: "w3a-001",
    q: "By the end of Week 3 Part A, you should be able to create:",
    options: [
      "A burndown chart, sprint backlog, and roadmap.",
      "An activity plan, a duration estimate, and a critical path / precedence network.",
      "A bug report and a regression test suite.",
      "A risk register and stakeholder matrix only.",
    ],
    correct: 1,
    explain: "Objectives: produce activity plan, estimate duration, create critical path & precedence network.",
    topic: "Planning",
  },
  {
    id: "w3a-002",
    q: "Which option corresponds to the BUILD path in build-or-buy?",
    options: ["Outsource", "Purchase off-the-shelf", "In-house development", "Lease a SaaS"],
    correct: 2,
    explain: "Build = in-house development. Buy = outsource / purchase OTS.",
    topic: "Build or buy",
  },
  {
    id: "w3a-003",
    q: "Which is NOT an advantage of off-the-shelf software?",
    options: [
      "Cheaper because development cost is spread across many customers.",
      "Can be trialled before buying.",
      "Customer owns and can change the source code.",
      "Software is available now — no development wait.",
    ],
    correct: 2,
    explain: "OTS users do NOT own the code and cannot change it — that's a disadvantage.",
    topic: "OTS",
  },
  {
    id: "w3a-004",
    q: "A KEY disadvantage of OTS software is:",
    options: [
      "Bugs are usually not fixed quickly.",
      "No competitive advantage — the customer has the same app as everyone else.",
      "It cannot be deployed to many users.",
      "It is always more expensive than in-house.",
    ],
    correct: 1,
    explain: "OTS gives no competitive advantage on its own; advantage can only come from how it is used.",
    topic: "OTS",
  },
  {
    id: "w3a-005",
    q: "Make-or-Buy worked example: lease $800/day vs purchase $12,000 + $400/day. The break-even is:",
    options: ["20 days", "25 days", "30 days", "40 days"],
    correct: 2,
    explain: "12,000 + 400d = 800d → 12,000 = 400d → d = 30 days.",
    topic: "Make-or-buy",
  },
  {
    id: "w3a-006",
    q: "Following the make-or-buy example, if you need the item for MORE than 30 days you should:",
    options: ["Lease", "Purchase", "Lease and then purchase", "Subscribe to a SaaS"],
    correct: 1,
    explain: "Above the break-even, purchase is more economical.",
    topic: "Make-or-buy",
  },
  {
    id: "w3a-007",
    q: "What does EV stand for in EVM?",
    options: ["Estimated Value", "Earned Value", "Expected Variance", "Evaluated Velocity"],
    correct: 1,
    explain: "EV = Earned Value — how much work has actually been completed in value terms.",
    topic: "EVM",
  },
  {
    id: "w3a-008",
    q: "What does PV represent?",
    options: [
      "How much money has been spent so far.",
      "How much work SHOULD be done by now (planned).",
      "How much value the project will return.",
      "Past velocity of the team.",
    ],
    correct: 1,
    explain: "PV = Planned Value — how much work should be done by now.",
    topic: "EVM",
  },
  {
    id: "w3a-009",
    q: "What is the formula for Cost Performance Index (CPI)?",
    options: ["CPI = AC / EV", "CPI = EV / AC", "CPI = EV / PV", "CPI = PV / AC"],
    correct: 1,
    explain: "CPI = EV / AC. >1 = under budget (good).",
    topic: "EVM",
  },
  {
    id: "w3a-010",
    q: "What is the formula for Schedule Performance Index (SPI)?",
    options: ["SPI = EV / AC", "SPI = PV / EV", "SPI = EV / PV", "SPI = AC / PV"],
    correct: 2,
    explain: "SPI = EV / PV. >1 = ahead of schedule (good).",
    topic: "EVM",
  },
  {
    id: "w3a-011",
    q: "If EV > PV, the project is:",
    options: ["Behind schedule", "On schedule", "Ahead of schedule", "Over budget"],
    correct: 2,
    explain: "EV > PV → ahead of schedule (earned more value than planned by now).",
    topic: "EVM",
  },
  {
    id: "w3a-012",
    q: "If EV < AC, the project is:",
    options: ["Under budget", "On budget", "Over budget", "Ahead of schedule"],
    correct: 2,
    explain: "EV < AC → over budget (spent more than the value earned).",
    topic: "EVM",
  },
  {
    id: "w3a-013",
    q: "Given PV=100, EV=100, AC=75, the project is:",
    options: [
      "On schedule, under budget",
      "Behind schedule, over budget",
      "Ahead of schedule, on budget",
      "On schedule, over budget",
    ],
    correct: 0,
    explain: "EV=PV → on schedule. EV>AC → under budget.",
    topic: "EVM",
  },
  {
    id: "w3a-014",
    q: "Given PV=100, EV=75, AC=100, the project is:",
    options: [
      "On schedule, on budget",
      "Behind schedule, over budget",
      "Ahead of schedule, under budget",
      "On schedule, under budget",
    ],
    correct: 1,
    explain: "EV<PV → behind schedule. EV<AC → over budget.",
    topic: "EVM",
  },
  {
    id: "w3a-015",
    q: "Given PV=75, EV=100, AC=100, the project is:",
    options: [
      "On schedule, on budget",
      "Behind schedule, under budget",
      "Ahead of schedule, on budget",
      "Ahead of schedule, over budget",
    ],
    correct: 2,
    explain: "EV>PV → ahead. EV=AC → on budget.",
    topic: "EVM",
  },
  {
    id: "w3a-016",
    q: "Which is NOT a reason to plan activities?",
    options: ["Feasibility assessment", "Detailed costing", "Motivation", "Eliminating risk entirely"],
    correct: 3,
    explain: "Five reasons: feasibility, resource allocation, detailed costing, motivation, coordination.",
    topic: "Planning",
  },
  {
    id: "w3a-017",
    q: "An activity in an activity plan must have:",
    options: [
      "A budget but not necessarily a duration.",
      "A clearly defined start and endpoint, usually marked by a tangible deliverable.",
      "At least three contributors.",
      "A formal client signature.",
    ],
    correct: 1,
    explain: "Each activity must have clear start/end (usually a tangible deliverable).",
    topic: "Planning",
  },
  {
    id: "w3a-018",
    q: "The activity-based approach to identifying activities effectively builds:",
    options: ["A Gantt chart", "A risk register", "An activity-based WBS", "A burndown chart"],
    correct: 2,
    explain: "Identifying high-level tasks and breaking them down produces an activity-based WBS.",
    topic: "Planning",
  },
  {
    id: "w3a-019",
    q: "A bar/Gantt chart shows:",
    options: [
      "Activities and dependencies as a graph.",
      "The project plan laid out against a time axis.",
      "Only resource availability.",
      "Only the critical chain.",
    ],
    correct: 1,
    explain: "Gantt = project plan on a time axis. Activity network = dependencies as a graph.",
    topic: "Scheduling tools",
  },
  {
    id: "w3a-020",
    q: "In Activity-on-Node (AoN), where is duration recorded?",
    options: [
      "On the arrows (links).",
      "On the nodes (boxes).",
      "On both nodes and links.",
      "Only at the start and end nodes.",
    ],
    correct: 1,
    explain: "AoN: nodes carry duration; links carry no duration.",
    topic: "AoN/AoA",
  },
  {
    id: "w3a-021",
    q: "Which is a rule of Activity-on-Arrow (AoA)?",
    options: [
      "Nodes are activities and have duration.",
      "Nodes are numbered sequentially; each event has earliest and latest dates.",
      "Links carry duration but nodes do not.",
      "Loops are allowed.",
    ],
    correct: 1,
    explain: "AoA: nodes are numbered events with earliest/latest dates; slack = late − early.",
    topic: "AoN/AoA",
  },
  {
    id: "w3a-022",
    q: "Float is best defined as:",
    options: [
      "The amount of time an activity can be delayed without delaying the next activity or the whole project.",
      "The slack between budget and actual cost.",
      "Time spent on rework.",
      "Time saved by crashing.",
    ],
    correct: 0,
    explain: "Float = delay tolerance without affecting successors or the whole project.",
    topic: "Float",
  },
  {
    id: "w3a-023",
    q: "Total Float (TF) is:",
    options: ["TF = LS − ES", "TF = ES − LS", "TF = EF − ES", "TF = LF − ES"],
    correct: 0,
    explain: "TF = LS − ES (also equal to LF − EF).",
    topic: "Float",
  },
  {
    id: "w3a-024",
    q: "Free Float (FF) is:",
    options: [
      "FF = LS(next) − ES(current)",
      "FF = ES(next) − EF(current)",
      "FF = LF(next) − EF(current)",
      "FF = EF − LS",
    ],
    correct: 1,
    explain: "FF = ES of the next activity − EF of the current.",
    topic: "Float",
  },
  {
    id: "w3a-025",
    q: "Boehm's seven techniques — which uses 'effort drivers'?",
    options: ["Expert judgement", "Algorithmic models", "Analogy", "Parkinson"],
    correct: 1,
    explain: "Algorithmic models use effort drivers (characteristics of system and environment).",
    topic: "Estimation",
  },
  {
    id: "w3a-026",
    q: "Which Boehm technique uses an actual completed similar project as the basis?",
    options: ["Analogy", "Parkinson", "Top-down", "Expert judgement"],
    correct: 0,
    explain: "Analogy uses actual effort of a similar completed project.",
    topic: "Estimation",
  },
  {
    id: "w3a-027",
    q: "Which Boehm technique sets the estimate equal to the available staff effort?",
    options: ["Parkinson", "Algorithmic", "Bottom-up", "Top-down"],
    correct: 0,
    explain: "Parkinson: the staff effort available becomes the estimate.",
    topic: "Estimation",
  },
  {
    id: "w3a-028",
    q: "Which Boehm technique picks a figure low enough to win the contract?",
    options: ["Expert judgement", "Price to win", "Top-down", "Analogy"],
    correct: 1,
    explain: "Price to win: estimate = low enough to win the contract.",
    topic: "Estimation",
  },
  {
    id: "w3a-029",
    q: "Top-down estimation works by:",
    options: [
      "Aggregating sized component tasks.",
      "Breaking down an overall estimate into component-task efforts.",
      "Using PERT three-point estimates per task.",
      "Adding a flat buffer to expert judgement.",
    ],
    correct: 1,
    explain: "Top-down breaks an overall estimate down into components. Bottom-up aggregates from components.",
    topic: "Estimation",
  },
  {
    id: "w3a-030",
    q: "Analogous (top-down) estimation is BEST characterised as:",
    options: [
      "Most accurate; used late in projects.",
      "Less costly and faster, but less accurate; used early.",
      "Always uses PERT internally.",
      "Independent of historical data.",
    ],
    correct: 1,
    explain: "Analogous is fast and cheap but less accurate — used early (Rough Order of Magnitude).",
    topic: "Estimation",
  },
  {
    id: "w3a-031",
    q: "Parametric estimation example: 4 hrs to cut 2 acres (no setup cost). Estimated hours to cut 8 acres?",
    options: ["8 hours", "12 hours", "16 hours", "32 hours"],
    correct: 2,
    explain: "Rate = 2 hrs/acre × 8 acres = 16 hours.",
    topic: "Estimation",
  },
  {
    id: "w3a-032",
    q: "What is the PERT three-point formula for expected duration?",
    options: [
      "t_e = (t_o + t_m + t_p) / 3",
      "t_e = (t_o + 4·t_m + t_p) / 6",
      "t_e = (4·t_o + t_m + t_p) / 6",
      "t_e = (t_o + 2·t_m + t_p) / 4",
    ],
    correct: 1,
    explain: "PERT: t_e = (t_o + 4·t_m + t_p) / 6. The 'most likely' is weighted 4×.",
    topic: "PERT",
  },
  {
    id: "w3a-033",
    q: "Compute PERT: t_o = 4, t_m = 6, t_p = 14. Expected duration:",
    options: ["6", "7", "8", "10"],
    correct: 1,
    explain: "(4 + 4·6 + 14)/6 = (4+24+14)/6 = 42/6 = 7.",
    topic: "PERT",
  },
  {
    id: "w3a-034",
    q: "Compute PERT: t_o = 2, t_m = 5, t_p = 8. Expected duration:",
    options: ["4", "5", "6", "7"],
    correct: 1,
    explain: "(2 + 4·5 + 8)/6 = (2+20+8)/6 = 30/6 = 5.",
    topic: "PERT",
  },
  {
    id: "w3a-035",
    q: "Contingency reserves can be expressed as:",
    options: [
      "A percentage of estimated duration or a fixed number of work periods.",
      "Always 10% of total cost.",
      "Only as a calendar date offset.",
      "Only by the customer's request.",
    ],
    correct: 0,
    explain: "Reserves are expressed as a percent of duration or a fixed number of work periods.",
    topic: "Contingency",
  },
  {
    id: "w3a-036",
    q: "Schedule Network Analysis techniques include all EXCEPT:",
    options: ["Critical Path Method", "Critical Chain Method", "Resource leveling", "Burndown velocity"],
    correct: 3,
    explain: "Techniques: CPM, Critical Chain, Resource leveling, What-if analysis, Scheduling tools.",
    topic: "Scheduling",
  },
  {
    id: "w3a-037",
    q: "The critical path is best defined as:",
    options: [
      "Any sequence of activities the customer must approve.",
      "The set of activities that must be completed on time or the whole project slips.",
      "Activities the manager personally oversees.",
      "Activities with the largest float.",
    ],
    correct: 1,
    explain: "Critical path = activities that, if delayed, delay the entire project (float = 0).",
    topic: "CPM",
  },
  {
    id: "w3a-038",
    q: "CPM helps identify all EXCEPT:",
    options: [
      "How long the entire project will take.",
      "The activities that determine total project time.",
      "Resource allocation planning for activities.",
      "The team's hourly cost rate.",
    ],
    correct: 3,
    explain: "CPM identifies total duration, critical activities, and assists resource allocation — not hourly costs.",
    topic: "CPM",
  },
];
