import type { MCQ } from "./types";

export const week2_1: MCQ[] = [
  {
    id: "w2a-001",
    q: "What does SDLC stand for?",
    options: ["System Design and Logic Cycle", "Software Development Life Cycle", "Software Delivery Life Chain", "Sequential Design Life Cycle"],
    correct: 1,
    explain: "SDLC = Software Development Life Cycle — divides development into distinct phases.",
    topic: "SDLC",
  },
  {
    id: "w2a-002",
    q: "Which of these is NOT named as a common SDLC model in the slides?",
    options: ["Waterfall", "Spiral", "Lean Six Sigma", "V-Model"],
    correct: 2,
    explain: "Named models: Waterfall, Agile, Spiral, V-Model, Incremental.",
    topic: "SDLC",
  },
  {
    id: "w2a-003",
    q: "In Waterfall, progress is primarily measured by:",
    options: ["Working software", "The amount of documentation produced", "Number of user stories closed", "Burndown velocity"],
    correct: 1,
    explain: "Waterfall is document-driven; progress is measured by amount of documentation.",
    topic: "Waterfall",
  },
  {
    id: "w2a-004",
    q: "Which statement is true about staffing in Waterfall?",
    options: [
      "One cross-functional team owns every phase.",
      "Staff are dedicated to each phase.",
      "Staff rotate continuously between phases.",
      "Staff are only assigned at the testing phase.",
    ],
    correct: 1,
    explain: "Waterfall keeps phases separated and staff dedicated to each phase.",
    topic: "Waterfall",
  },
  {
    id: "w2a-005",
    q: "A defining weakness of Waterfall is that the customer is involved:",
    options: [
      "Throughout the project, in every sprint.",
      "Only during the initial (requirements) phase.",
      "Only during the final acceptance phase.",
      "Only when changes are needed.",
    ],
    correct: 1,
    explain: "Limited customer contact — only during the initial requirements phase.",
    topic: "Waterfall",
  },
  {
    id: "w2a-006",
    q: "Waterfall delivers software:",
    options: ["In small increments", "Once, at the end of the project", "At the end of every sprint", "Continuously"],
    correct: 1,
    explain: "Software is released only at the end, a key Waterfall weakness.",
    topic: "Waterfall",
  },
  {
    id: "w2a-007",
    q: "Why is documentation a 'support' feature in Waterfall?",
    options: [
      "It is required by law.",
      "It supports personnel changes — a new person can pick up the docs.",
      "It speeds up code review.",
      "It eliminates the need for testing.",
    ],
    correct: 1,
    explain: "Documents support personnel continuity when staff change.",
    topic: "Waterfall",
  },
  {
    id: "w2a-008",
    q: "Waterfall's 'big issue' is best summarised as:",
    options: ["Too few documents", "Requirements up-front", "No testing phase", "No team meetings"],
    correct: 1,
    explain: "The big issue: Waterfall demands all requirements be fixed up-front.",
    topic: "Waterfall",
  },
  {
    id: "w2a-009",
    q: "Which idea is a founding assumption of Agile?",
    options: [
      "There is one universal recipe for great software.",
      "Changes are unavoidable.",
      "Developers should not have opinions on direction.",
      "Quality is independent of people.",
    ],
    correct: 1,
    explain: "Agile assumes changes are unavoidable; quality strongly depends on people.",
    topic: "Agile basics",
  },
  {
    id: "w2a-010",
    q: "Agile development is best described as:",
    options: [
      "Phase-by-phase with one final delivery.",
      "Iterative and incremental — each iteration improved by the next.",
      "Single-shot delivery after full requirements.",
      "A sequential set of documentation milestones.",
    ],
    correct: 1,
    explain: "Agile is iterative: one iteration is followed by improvements in the next.",
    topic: "Agile basics",
  },
  {
    id: "w2a-011",
    q: "Which is the FIRST value in the Agile Manifesto?",
    options: [
      "Working software over comprehensive documentation",
      "Individuals and interactions over processes and tools",
      "Customer collaboration over contract negotiation",
      "Responding to change over following a plan",
    ],
    correct: 1,
    explain: "Value #1: Individuals and interactions over processes and tools.",
    topic: "Agile values",
  },
  {
    id: "w2a-012",
    q: "Complete the Agile value: 'Working software over ____'.",
    options: ["Detailed specifications", "Comprehensive documentation", "Project plans", "Contract negotiation"],
    correct: 1,
    explain: "Value #2: Working software over comprehensive documentation.",
    topic: "Agile values",
  },
  {
    id: "w2a-013",
    q: "Which of these is the third Agile value?",
    options: [
      "Customer collaboration over contract negotiation",
      "Working software over plans",
      "Team autonomy over hierarchy",
      "Speed over correctness",
    ],
    correct: 0,
    explain: "Value #3: Customer collaboration over contract negotiation.",
    topic: "Agile values",
  },
  {
    id: "w2a-014",
    q: "The Agile values use 'X over Y' wording. The correct interpretation is:",
    options: [
      "The right-hand items are worthless.",
      "The left-hand items are valued more, but the right-hand items still have value.",
      "Only the left-hand items matter.",
      "Both sides have equal weight.",
    ],
    correct: 1,
    explain: "The right-hand items still have value, but left items are valued more.",
    topic: "Agile values",
  },
  {
    id: "w2a-015",
    q: "How many principles are in the Agile Manifesto?",
    options: ["4", "7", "12", "15"],
    correct: 2,
    explain: "There are 4 values and 12 principles.",
    topic: "Agile principles",
  },
  {
    id: "w2a-016",
    q: "The HIGHEST priority of Agile is:",
    options: [
      "Cutting documentation costs.",
      "Satisfying the customer through early and continuous delivery of valuable software.",
      "Eliminating planning.",
      "Empowering management.",
    ],
    correct: 1,
    explain: "Principle #1: Customer satisfaction through early and continuous software delivery.",
    topic: "Agile principles",
  },
  {
    id: "w2a-017",
    q: "Which is the primary measure of progress in Agile?",
    options: ["Documentation", "Working software", "Hours logged", "Burndown slope"],
    correct: 1,
    explain: "Principle #7: Working software is the primary measure of progress.",
    topic: "Agile principles",
  },
  {
    id: "w2a-018",
    q: "Which Agile principle promotes long-term project health?",
    options: [
      "Bursts of overtime when needed.",
      "Sustainable (consistent) development pace.",
      "Doubling staff at each iteration.",
      "Hiring contractors at the end.",
    ],
    correct: 1,
    explain: "Principle #8: Agile processes promote a sustainable (consistent) pace.",
    topic: "Agile principles",
  },
  {
    id: "w2a-019",
    q: "Which Agile principle is about KEEPING IT SIMPLE?",
    options: [
      "Simplicity — develop just enough to get the job done for right now.",
      "Reduce documentation to zero.",
      "Use the simplest framework available.",
      "Avoid testing where possible.",
    ],
    correct: 0,
    explain: "Principle #10: Simplicity — just enough for now.",
    topic: "Agile principles",
  },
  {
    id: "w2a-020",
    q: "Which dimension differs MOST between Waterfall and Agile?",
    options: [
      "Whether requirements can change after they're set.",
      "Whether the team uses a kanban board.",
      "Whether there is a project manager.",
      "Whether the project has a budget.",
    ],
    correct: 0,
    explain: "Waterfall fixes requirements up-front; Agile lets requirements change at any time.",
    topic: "Compare",
  },
  {
    id: "w2a-021",
    q: "In a Waterfall→Agile transition, the lecture identifies the hardest issue as:",
    options: [
      "Buying new project tools.",
      "Adopting a kanban board.",
      "Shifting to an Agile mindset (a cultural shift).",
      "Hiring more developers.",
    ],
    correct: 2,
    explain: "Transitioning to an Agile mindset is the hardest PM issue — it's a cultural shift.",
    topic: "Compare",
  },
  {
    id: "w2a-022",
    q: "Which of these is NOT an Agile framework named in the course?",
    options: ["Scrum", "Kanban", "Extreme Programming", "RAD"],
    correct: 3,
    explain: "Course-named Agile frameworks: Scrum, Kanban, XP.",
    topic: "Agile frameworks",
  },
  {
    id: "w2a-023",
    q: "Which mnemonic captures all FIVE Scrum values?",
    options: ["S-M-A-R-T", "C-C-R-F-O", "I-C-C-F", "P-O-S-M-T"],
    correct: 1,
    explain: "C-C-R-F-O: Courage, Commitment, Respect, Focus, Openness.",
    topic: "Scrum values",
  },
  {
    id: "w2a-024",
    q: "Which Scrum value means the team is 'aware of what each other is working on'?",
    options: ["Courage", "Respect", "Openness", "Focus"],
    correct: 2,
    explain: "Openness — everyone aware of the work and how it moves the project toward its goals.",
    topic: "Scrum values",
  },
  {
    id: "w2a-025",
    q: "Which Scrum value is about 'standing up for the project against pushback'?",
    options: ["Commitment", "Courage", "Respect", "Focus"],
    correct: 1,
    explain: "Courage — the team stands up for the project and lives by its values.",
    topic: "Scrum values",
  },
  {
    id: "w2a-026",
    q: "Which Scrum value means 'team members trust each other to do a good job'?",
    options: ["Focus", "Respect", "Openness", "Commitment"],
    correct: 1,
    explain: "Respect — trust each other; the Scrum Master should grow mutual respect.",
    topic: "Scrum values",
  },
  {
    id: "w2a-027",
    q: "Which Scrum value warns that switching people among activities wastes time and money?",
    options: ["Focus", "Openness", "Courage", "Commitment"],
    correct: 0,
    explain: "Focus — the team is focused on the sprint; switching people wastes time/money.",
    topic: "Scrum values",
  },
  {
    id: "w2a-028",
    q: "Which is NOT one of the three Scrum roles?",
    options: ["Product Owner (PO)", "Scrum Master (SM)", "Team Member (TM)", "Release Manager (RM)"],
    correct: 3,
    explain: "Three Scrum roles: Product Owner, Scrum Master, Team Member.",
    topic: "Scrum roles",
  },
  {
    id: "w2a-029",
    q: "Decomposition in the Agile model means:",
    options: [
      "Big projects split into small parts (and big companies into small teams).",
      "Removing testing from the lifecycle.",
      "Reducing the number of stakeholders.",
      "Splitting code into smaller files.",
    ],
    correct: 0,
    explain: "Agile decomposes complex work into small parts and large companies into small teams.",
    topic: "Agile basics",
  },
  {
    id: "w2a-030",
    q: "Agile is best summarised compared to project management as:",
    options: [
      "Agile is a synonym for project management.",
      "Agile is a specific methodology; project management is the broader umbrella.",
      "Project management is a subset of Agile.",
      "They have no overlap.",
    ],
    correct: 1,
    explain: "Agile = a specific methodology. Project management = broader umbrella that includes Agile, Waterfall, etc.",
    topic: "Compare",
  },
  {
    id: "w2a-031",
    q: "In a Waterfall project, change to requirements after the requirements phase is:",
    options: [
      "Welcomed at any time.",
      "Embraced via retrospectives.",
      "Not possible (or very hard).",
      "Performed once per sprint.",
    ],
    correct: 2,
    explain: "Waterfall: changes to requirements are not possible after the requirements phase.",
    topic: "Waterfall",
  },
  {
    id: "w2a-032",
    q: "Which Agile principle emphasises FACE-TO-FACE?",
    options: [
      "Principle 6 — enable face-to-face interactions.",
      "Principle 10 — simplicity.",
      "Principle 2 — accommodate change.",
      "Principle 7 — working software.",
    ],
    correct: 0,
    explain: "Principle #6: Enable face-to-face interactions.",
    topic: "Agile principles",
  },
];
